# Site settings
course_name: History of Magic
course_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ornare aliquam mattis. Donec hendrerit sollicitudin urna. Aliquam venenatis rutrum velit, at lobortis dui cursus a. Nam varius metus in turpis maximus, ut rhoncus tellus dictum. In aliquam tortor nec mi dapibus, sit amet vehicula dolor auctor."
course_semester: "Fall 1998"
description: |
    Instructor: Alan Turing

baseurl: "/base-url" # the subpath of your site, e.g. /blog/
url: "http://iust-courses.github.io/" # the base hostname & protocol for your site
githubdir: "username/repo"

# Author/user information

schoolurl: "https://hogwarts.edu"
schoolname: "Hogwarts"
twitter_username: username 

address: |
    School of Witchcraft and Wizardry
    Hogwarts
    Scotland


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

header_color: "#336699"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"



# plugins:
#     - jekyll-feed
